spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000 # 5
      connection-timeout: 30000 # 30
      max-lifetime: 1800000 # 30
      validation-timeout: 5000 # 5
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

logging:
  level:
    root: info